services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: recipe_db_dev
      POSTGRES_USER: recipe_ai_dev_user
      POSTGRES_PASSWORD: recipe_ai_dev_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata: