services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: recipe_db_dev
      POSTGRES_USER: recipe_ai_dev_user
      POSTGRES_PASSWORD: recipe_ai_dev_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata: